apiVersion: app.k8s.io/v1beta1
kind: Applications
metadata:
  labels:
    app: nginx-app-details
  name: nginx-app-3
  namespace: ns-sub-1
spec:
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
  - group: core.hybridapp.io
    kind: Deployable
  selector:
    matchLabels:
      app: nginx-app-details
status: {}